<!--<section class="selling-wrapper">-->

<div class="container">
	<div class="row">
    <div class="col-md-12">
    <h2 class="mtn-c wh-color"> Top selling products </h2>
    <p>
                Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. 
                </p>
      </div>     
     
     
    </div>

</div>

<div class="jcarousel-wrapper"> 
           
      <div class="jcarousel-selling-products">
    	<ul>
        <li> 
        	<div class="selling-box">
            <div class="save-box"> Save 20% </div> 
            <div class="selling-img"> <img src="images/selling-pic1.jpg" border="0" alt=""> </div>
            	<div class="selling-wh-box">
                	
                	<div class="selling-share-prt">
                    	<div class="selling-sh-icon text-right"> <a href="#" class="share-icon-cart"><i class="lni lni-share-alt-1"></i></a> <a href="#" class="heart-icon-cart"> 
                                 <i class="lni lni-heart-filled"></i> </a>  </div>
                    </div>
                    <div class="selling-hd font-17 font-wg500 black-color"> SmartBiz </div>
                    <div class="selling-text-block font-13 txt-color-b-7"> Low cost mobile tariff plan from N1,000 </div>
                    <div class="selling-icon-block"> 
                    	<ul>
                        	<li> <img src="images/group-7.png" border="0" alt=""> </li>
                            <li> + </li>
                            <li> <img src="images/group-4.png" border="0" alt=""> </li>
                             <li> + </li>
                            <li> <img src="images/group-5.png" border="0" alt=""> </li>
                             <li> + </li>
                            <li> <img src="images/group-6.png" border="0" alt=""> </li>
                        </ul>
                    </div>
                    <div class="selling-read-m-block"><a href="#" class="mtn-btn-link-more">Read more</a> </div>
                </div>
            
            </div>
        
        </li>
        <li> 
        
        <div class="selling-box">
        <div class="mtn-new-pro-btn"><i class="fa fa-check-circle" aria-hidden="true"></i>  New  </div>
            <div class="selling-img"> <img src="images/selling-pic2.jpg" border="0" alt=""> </div>
            	<div class="selling-wh-box">
                	<div class="selling-share-prt">
                    	<div class="selling-sh-icon text-right"> <a href="#" class="share-icon-cart"><i class="lni lni-share-alt-1"></i></a> <a href="#" class="heart-icon-cart"> 
                                 <i class="lni lni-heart-filled"></i> </a>  </div>
                    </div>
                    <div class="selling-hd font-17 font-wg500 black-color"> HyNetFlex </div>
                    <div class="selling-text-block font-13 txt-color-b-7"> Wireless broadband internet solutions with fast browsing and download. </div>
                    <div class="selling-icon-block"> 
                    	<ul>
                        	<li> <img src="images/group-7.png" border="0" alt=""> </li>
                            <li> + </li>
                            <li> <img src="images/group-4.png" border="0" alt=""> </li>
                             <li> + </li>
                            <li> <img src="images/group-5.png" border="0" alt=""> </li>
                       
                        </ul>
                    </div>
                    <div class="selling-read-m-block"><a href="#" class="mtn-btn-link-more">Read more</a> </div>
                </div>
            
            </div>
        
        </li>
         <li> 
         
         <div class="selling-box">
         <div class="save-box"> Save 20% </div> 
            <div class="selling-img"> <img src="images/selling-pic3.jpg" border="0" alt=""> </div>
            	<div class="selling-wh-box">
                	<div class="selling-share-prt">
                    	<div class="selling-sh-icon text-right"> <a href="#" class="share-icon-cart"><i class="lni lni-share-alt-1"></i></a> <a href="#" class="heart-icon-cart"> 
                                 <i class="lni lni-heart-filled"></i> </a>  </div>
                    </div>
                    <div class="selling-hd font-17 font-wg500 black-color"> Connect more </div>
                    <div class="selling-text-block font-13 txt-color-b-7"> Low cost mobile tariff plan With data bundles </div>
                    <div class="selling-icon-block"> 
                    	<ul>
                        	<li> <img src="images/group-7.png" border="0" alt=""> </li>
                            <li> + </li>
                            <li> <img src="images/group-4.png" border="0" alt=""> </li>
                             <li> + </li>
                            <li> <img src="images/group-5.png" border="0" alt=""> </li>
                             <li> + </li>
                            <li> <img src="images/group-6.png" border="0" alt=""> </li>
                        </ul>
                    </div>
                    <div class="selling-read-m-block"><a href="#" class="mtn-btn-link-more">Read more</a> </div>
                </div>
            
            </div>
         
         </li>
        <li> 
        
        <div class="selling-box">
            <div class="selling-img"> <img src="images/selling-pic1.jpg" border="0" alt=""> </div>
            	<div class="selling-wh-box">
                	<div class="selling-share-prt">
                    	<div class="selling-sh-icon text-right"> <a href="#" class="share-icon-cart"><i class="lni lni-share-alt-1"></i></a> <a href="#" class="heart-icon-cart"> 
                                 <i class="lni lni-heart-filled"></i> </a>  </div>
                    </div>
                    <div class="selling-hd font-17 font-wg500 black-color"> SmartBiz </div>
                    <div class="selling-text-block font-13 txt-color-b-7"> Low cost mobile tariff plan from N1,000 </div>
                    <div class="selling-icon-block"> 
                    	<ul>
                        	<li> <img src="images/group-7.png" border="0" alt=""> </li>
                            <li> + </li>
                            <li> <img src="images/group-4.png" border="0" alt=""> </li>
                             <li> + </li>
                            <li> <img src="images/group-5.png" border="0" alt=""> </li>
                             <li> + </li>
                            <li> <img src="images/group-6.png" border="0" alt=""> </li>
                        </ul>
                    </div>
                    <div class="selling-read-m-block"><a href="#" class="mtn-btn-link-more">Read more</a> </div>
                </div>
            
            </div>
        
        </li>
        	
          
        
        </ul>
    
    </div>          
    
    <a href="#" class="jcarousel-selling-products-control-prev" data-jcarouselcontrol="true"><i class="fa fa-angle-left" aria-hidden="true"></i></a>
    <a href="#" class="jcarousel-selling-products-control-next" data-jcarouselcontrol="true"><i class="fa fa-angle-right" aria-hidden="true"></i></a>
    <p class="jcarousel-selling-products-pagination" data-jcarouselpagination="true"> </p>
    
    </div>

<!--</section>-->