
<div class="container position-relative">
	<div class="mtn-s-text-b text-right"> 
    
    	<h2 class="mtn-c  text-left text-white"> Explore more MTN services
    <span class=" pt-1 font-15 d-block font-wg400 wh-color-7">
    Our data plans fit your lifestyle and give you the best value for money
    </span>
    
     </h2>
     
     <div class="service-box-block">
     	<div class="font-17 font-wg500 serv-hd"> SME Datashare </div>
        <div class="serv-cont"> 
        	<div class="font-15 serv-text-p"> 
            	Allows business owners to buy data bundles and share with their staff
            </div>
            
            <div class="view-m-btn"> <a href="#" class="mtn-btn-link-more">View more</a> </div>
        
        </div>
     
     </div>
     
     <div class="service-box-block">
     	<div class="font-17 font-wg500 serv-hd"> Dedicated internet service </div>
        <div class="serv-cont"> 
        	<div class="font-15 serv-text-p"> 
            	Get Dedicated Bandwidth with reliable connectivity backed by Enterprise-Grade SLA's
            </div>
            
            <div class="view-m-btn"> <a href="#" class="mtn-btn-link-more">View more</a> </div>
        
        </div>
     
     </div>
    
    </div>

</div>

<div class="service-banner-mtn"> <img src="images/services-banner-mtn.jpg" border="0" alt=""> </div>

 