
<div class="container">
	<div class="row">
	<div class="col-md-12"> <h2 class="mtn-c black-color text-center"> Explore by categories 
    <span class=" pt-1 font-17 d-block font-wg300 txt-color-b-7">
    There's everything, for everyone
    </span>
    
     </h2> </div>
</div>

	<div class="row">
    	<div class="col-lg-2 col-md-4 col-sm-4"> 
    
    <div class="mtn-box-link">
        	<a href="#" class="mtn-box-prt">
            	<div class="mtn-box-icon"> <img src="images/icons-subscription.png" border="0" alt="">       </div>
                <div class="mtn-box-text"> MTN Devices</div>
            </a>
        </div>
    
    </div>
    
    	<div class="col-lg-2 col-md-4 col-sm-4"> 
    
    <div class="mtn-box-link">
        	<a href="#" class="mtn-box-prt">
            	<div class="mtn-box-icon"> <img src="images/icons-contact-us-24.png" border="0" alt="">       </div>
                <div class="mtn-box-text"> Voices services</div>
            </a>
        </div>
    
    </div>
    	<div class="col-lg-2 col-md-4 col-sm-4"> 
    
    <div class="mtn-box-link">
        	<a href="#" class="mtn-box-prt">
            	<div class="mtn-box-icon"> <img src="images/categoris-shape.png" border="0" alt="">       </div>
                <div class="mtn-box-text"> Broadband services </div>
            </a>
        </div>
    
    </div>
    
    	<div class="col-lg-2 col-md-4 col-sm-4"> 
    
    <div class="mtn-box-link">
        	<a href="#" class="mtn-box-prt">
            	<div class="mtn-box-icon"> <img src="images/computer-laptop.png" border="0" alt="">       </div>
                <div class="mtn-box-text"> Digital services </div>
            </a>
        </div>
    
    </div>
    
    	<div class="col-lg-2 col-md-4 col-sm-4"> 
    
    <div class="mtn-box-link">
        	<a href="#" class="mtn-box-prt">
            	<div class="mtn-box-icon"> <img src="images/iot-icon.jpg" border="0" alt="">       </div>
                <div class="mtn-box-text"> IOT </div>
            </a>
        </div>
    
    </div>
    
    	<div class="col-lg-2 col-md-4 col-sm-4"> 
    
    <div class="mtn-box-link">
        	<a href="#" class="mtn-box-prt">
            	<div class="mtn-box-icon"> <img src="images/icons-bbc-minute.png" border="0" alt="">       </div>
                <div class="mtn-box-text"> Infrastructure services </div>
            </a>
        </div>
    
    </div>
    
    	
    
    </div>

</div>

