<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

$target = $block->getTarget();
$label = $block->getLabel();
?>
<a class="action skip <?= $block->escapeHtmlAttr($target) ?>"
   href="#<?= $block->escapeHtmlAttr($target) ?>">
    <span>
        <?= $block->escapeHtml($label) ?>
    </span>
</a>
<div class="header-top"> 
    <?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('header-links')->toHtml();;?>
</div>
